name: traccar_manager
description: "Mrigel Tracking System"
publish_to: "none"
# version: 5.1.5+58
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  app_links: ^6.4.0
  firebase_analytics: ^11.6.0
  firebase_core: ^3.15.2
  firebase_crashlytics: ^4.3.10
  firebase_messaging: ^15.2.10
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  http: ^1.4.0
  local_auth: ^2.3.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  rate_my_app: ^2.3.2
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.10
  url_launcher: ^6.3.2
  webview_flutter: ^4.11.0
  webview_flutter_android: ^4.8.2
  webview_flutter_wkwebview: ^3.22.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 22 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff" # You can use a color or image for the background
  adaptive_icon_foreground: "assets/images/logo.png" # For adaptive icons on Android

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # - .env
    # - assets/translations/
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg
